# Generated by Django 2.2.1 on 2020-05-26 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ESearch', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postsearch',
            options={},
        ),
    ]
