# Generated by Django 2.2.1 on 2020-06-17 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0002_auto_20200605_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='title',
            field=models.CharField(error_messages={'unique': 'This title already used.'}, max_length=250, unique=True),
        ),
    ]
