# Generated by Django 2.2.1 on 2020-04-20 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('game_url', models.CharField(max_length=300, null=True)),
                ('image_url', models.CharField(max_length=300, null=True)),
                ('category', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'tbl_games',
            },
        ),
    ]
