# Generated by Django 2.2.1 on 2020-05-22 06:46

import Games.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Games', '0002_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddS3File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=Games.models.directory_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tbl_s3_file',
            },
        ),
    ]
