# Generated by Django 2.2.1 on 2020-04-16 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=20)),
                ('post_text', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tbl_post',
            },
        ),
        migrations.AlterField(
            model_name='server',
            name='hosting_os',
            field=models.CharField(choices=[('window', 'window'), ('linux', 'linux')], default='window', max_length=20),
        ),
        migrations.AlterField(
            model_name='server',
            name='plan_id',
            field=models.CharField(default='P101', max_length=15),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=100)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.Post')),
            ],
            options={
                'db_table': 'tbl_comments',
            },
        ),
    ]
