# Generated by Django 2.2.1 on 2020-04-22 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_comments_post'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='server',
            index=models.Index(fields=['plan_id', 'hosting_os'], name='tbl_servers_plan_id_d5017a_idx'),
        ),
    ]
