# Generated by Django 2.2.1 on 2020-04-22 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_auto_20200422_1132'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='server',
            name='tbl_servers_plan_id_d5017a_idx',
        ),
        migrations.AddIndex(
            model_name='server',
            index=models.Index(fields=['plan_id'], name='tbl_servers_plan_id_b8cf7b_idx'),
        ),
        migrations.AddIndex(
            model_name='server',
            index=models.Index(fields=['hosting_os'], name='tbl_servers_hosting_8ef2ab_idx'),
        ),
    ]
