# Generated by Django 2.2.1 on 2020-06-17 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_article_publication'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
