# Generated by Django 2.2.1 on 2020-07-17 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_auto_20200617_2241'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practice_duration', models.IntegerField(default=0)),
                ('day', models.DateField()),
            ],
            options={
                'db_table': 'tbl_assigment',
            },
        ),
    ]
